language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
before_script:
  - psql -c 'create database theodinproject_test;' -U postgres
script: xvfb-run bundle exec rake
test:
  adapter: postgresql
  database: theodinproject_test
